"""add new sub to user

Revision ID: 04fe0bf78dbd
Revises: 3cd49629a7ec
Create Date: 2025-07-26 03:35:34.659472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fe0bf78dbd'
down_revision: Union[str, Sequence[str], None] = '3cd49629a7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('end_sub_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'end_sub_time')
    # ### end Alembic commands ###
