"""fix

Revision ID: 125ff72079a0
Revises: 04f7081bf6e3
Create Date: 2025-09-09 09:10:43.415903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125ff72079a0'
down_revision: Union[str, Sequence[str], None] = '04f7081bf6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('created_by', sa.BigInteger(), nullable=False, server_default='455205382'))
    op.create_foreign_key(None, 'broadcasts', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'broadcasts', type_='foreignkey')
    op.drop_column('broadcasts', 'created_by')
    # ### end Alembic commands ###
