"""add_new_fileld

Revision ID: 193033b605bb
Revises: 74e45d0468ba
Create Date: 2025-08-19 18:13:39.449514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '193033b605bb'
down_revision: Union[str, Sequence[str], None] = '74e45d0468ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analize_payment_service_quantities', 'service_type',
               existing_type=postgresql.ENUM('ANALYSIS', 'SHORT_BOARD', name='paymentservicetype'),
               type_=sa.Enum('MATCH', 'MONEYGAME', 'SHORT_BOARD', name='servicetype'),
               existing_nullable=False)
    op.alter_column('user_analize_payment_services', 'service_type',
               existing_type=postgresql.ENUM('ANALYSIS', 'SHORT_BOARD', name='paymentservicetype'),
               type_=sa.Enum('MATCH', 'MONEYGAME', 'SHORT_BOARD', name='servicetype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_analize_payment_services', 'service_type',
               existing_type=sa.Enum('MATCH', 'MONEYGAME', 'SHORT_BOARD', name='servicetype'),
               type_=postgresql.ENUM('ANALYSIS', 'SHORT_BOARD', name='paymentservicetype'),
               existing_nullable=False)
    op.alter_column('analize_payment_service_quantities', 'service_type',
               existing_type=sa.Enum('MATCH', 'MONEYGAME', 'SHORT_BOARD', name='servicetype'),
               type_=postgresql.ENUM('ANALYSIS', 'SHORT_BOARD', name='paymentservicetype'),
               existing_nullable=False)
    # ### end Alembic commands ###
