"""add lang

Revision ID: 1e476322d4d4
Revises: 7a2803c3d741
Create Date: 2025-07-25 02:21:51.257094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e476322d4d4'
down_revision: Union[str, Sequence[str], None] = '7a2803c3d741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lang_code', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lang_code')
    # ### end Alembic commands ###
