"""update

Revision ID: 21c7406333d7
Revises: 5bbfcd7d7443
Create Date: 2025-07-31 06:02:03.986655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c7406333d7'
down_revision: Union[str, Sequence[str], None] = '5bbfcd7d7443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analize_payments', sa.Column('duration_days', sa.Integer(), nullable=True))
    op.add_column('analize_payments', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user_analize_payments', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user_promocode', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_promocode', 'is_active')
    op.drop_column('user_analize_payments', 'is_active')
    op.drop_column('analize_payments', 'is_active')
    op.drop_column('analize_payments', 'duration_days')
    # ### end Alembic commands ###
