"""fix

Revision ID: 22f3316e9342
Revises: a4bde3264805
Create Date: 2025-09-13 09:55:55.032560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f3316e9342'
down_revision: Union[str, Sequence[str], None] = 'a4bde3264805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages_for_new',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lang_code', sa.String(length=3), nullable=False),
    sa.Column('dispatch_day', sa.String(), nullable=False),
    sa.Column('dispatch_time', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_for_new')
    # ### end Alembic commands ###
