"""fix

Revision ID: 2883522269c4
Revises: eba777a3ad10
Create Date: 2025-08-02 20:47:25.354373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2883522269c4'
down_revision: Union[str, Sequence[str], None] = 'eba777a3ad10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promocode', 'activate_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user_analize_payments', sa.Column('current_analize_balance', sa.Integer(), nullable=False))
    op.add_column('user_promocode', sa.Column('current_analize_balance', sa.Integer(), nullable=True))
    op.drop_column('users', 'analiz_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('analiz_balance', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_column('user_promocode', 'current_analize_balance')
    op.drop_column('user_analize_payments', 'current_analize_balance')
    op.alter_column('promocode', 'activate_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
