"""update promo

Revision ID: 48d1e7f79cd8
Revises: 489c23882916
Create Date: 2026-04-15 19:35:38.625248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '48d1e7f79cd8'
down_revision: Union[str, Sequence[str], None] = '489c23882916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    promocode_type_enum = postgresql.ENUM(
        "REGULAR",
        "CARDS",
        name="promocodetype",
    )
    promocode_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('promocode_content_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promocode_id', sa.Integer(), nullable=False),
    sa.Column('content_card_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_card_id'], ['content_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promocode_id'], ['promocode.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promocode_id', 'position', name='uq_promocode_content_cards_promocode_id_position')
    )
    op.add_column(
        'promocode',
        sa.Column(
            'promocode_type',
            sa.Enum('REGULAR', 'CARDS', name='promocodetype'),
            nullable=False,
            server_default='REGULAR',
        ),
    )
    op.add_column('promocode', sa.Column('cards_issue_quantity', sa.Integer(), nullable=True))
    op.add_column('user_content_cards', sa.Column('source_user_promocode_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_user_content_cards_source_user_promocode_id',
        'user_content_cards',
        'user_promocode',
        ['source_user_promocode_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.add_column('user_promocode', sa.Column('issued_cards_count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('promocode', 'promocode_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_promocode', 'issued_cards_count')
    op.drop_constraint(
        'fk_user_content_cards_source_user_promocode_id',
        'user_content_cards',
        type_='foreignkey',
    )
    op.drop_column('user_content_cards', 'source_user_promocode_id')
    op.drop_column('promocode', 'cards_issue_quantity')
    op.drop_column('promocode', 'promocode_type')
    op.drop_table('promocode_content_cards')
    postgresql.ENUM(
        "REGULAR",
        "CARDS",
        name="promocodetype",
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
