"""Add detailed_analyzes relationship to User

Revision ID: 4f91f36c5536
Revises: 6f23594642c9
Create Date: 2025-07-21 04:11:14.761597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f91f36c5536'
down_revision: Union[str, Sequence[str], None] = '6f23594642c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detailed_analyzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('player_name', sa.String(length=50), nullable=False),
    sa.Column('total_moves', sa.Integer(), nullable=False),
    sa.Column('unforced_moves', sa.Integer(), nullable=False),
    sa.Column('unmarked_moves', sa.Integer(), nullable=False),
    sa.Column('moves_marked_doubtful', sa.Integer(), nullable=False),
    sa.Column('moves_marked_bad', sa.Integer(), nullable=False),
    sa.Column('moves_marked_very_bad', sa.Integer(), nullable=False),
    sa.Column('error_rate_chequer', sa.Float(), nullable=False),
    sa.Column('chequerplay_rating', sa.String(), nullable=False),
    sa.Column('rolls_marked_very_lucky', sa.Integer(), nullable=False),
    sa.Column('rolls_marked_lucky', sa.Integer(), nullable=False),
    sa.Column('rolls_unmarked', sa.Integer(), nullable=False),
    sa.Column('rolls_marked_unlucky', sa.Integer(), nullable=False),
    sa.Column('rolls_marked_very_unlucky', sa.Integer(), nullable=False),
    sa.Column('luck_rating', sa.String(), nullable=False),
    sa.Column('total_cube_decisions', sa.Integer(), nullable=False),
    sa.Column('close_or_actual_cube_decisions', sa.Integer(), nullable=False),
    sa.Column('doubles', sa.Integer(), nullable=False),
    sa.Column('takes', sa.Integer(), nullable=False),
    sa.Column('passes', sa.Integer(), nullable=False),
    sa.Column('missed_doubles_below_cp', sa.Float(), nullable=False),
    sa.Column('missed_doubles_above_cp', sa.Float(), nullable=False),
    sa.Column('wrong_doubles_below_dp', sa.Float(), nullable=False),
    sa.Column('wrong_doubles_above_tg', sa.Float(), nullable=False),
    sa.Column('wrong_takes', sa.Float(), nullable=False),
    sa.Column('wrong_passes', sa.Float(), nullable=False),
    sa.Column('error_rate_cube', sa.Float(), nullable=False),
    sa.Column('cube_decision_rating', sa.String(), nullable=False),
    sa.Column('error_rate_total', sa.Float(), nullable=False),
    sa.Column('snowie_error_rate', sa.Float(), nullable=False),
    sa.Column('overall_rating', sa.String(), nullable=False),
    sa.Column('actual_result', sa.Float(), nullable=False),
    sa.Column('luck_adjusted_result', sa.Float(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('game_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detailed_analyzes')
    # ### end Alembic commands ###
