"""dd file fields to nalysis

Revision ID: 6f23594642c9
Revises: c3dbbcad4b70
Create Date: 2025-07-21 03:54:52.045126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f23594642c9'
down_revision: Union[str, Sequence[str], None] = 'c3dbbcad4b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyzes', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('analyzes', sa.Column('file_path', sa.String(length=255), nullable=True))
    op.add_column('analyzes', sa.Column('game_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('player_username', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'player_username')
    op.drop_column('analyzes', 'game_id')
    op.drop_column('analyzes', 'file_path')
    op.drop_column('analyzes', 'file_name')
    # ### end Alembic commands ###
