"""fix

Revision ID: 74e45d0468ba
Revises: 4897209019f2
Create Date: 2025-08-19 06:42:06.748734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e45d0468ba'
down_revision: Union[str, Sequence[str], None] = '4897209019f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analize_payments', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analize_payments', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
