"""fix

Revision ID: 7a2803c3d741
Revises: 4f91f36c5536
Create Date: 2025-07-21 06:44:31.682189

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a2803c3d741"
down_revision: Union[str, Sequence[str], None] = "4f91f36c5536"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column(
        "detailed_analyzes", sa.Column("rolls_rate_chequer", sa.Float(), nullable=True)
    )

    # Update existing records with default value
    op.execute("UPDATE detailed_analyzes SET rolls_rate_chequer = 0.0")

    # Make the column non-nullable
    op.alter_column(
        "detailed_analyzes",
        "rolls_rate_chequer",
        existing_type=sa.Float(),
        nullable=False,
        server_default=sa.text("0.0"),
    )

    # Drop other columns
    op.drop_column("detailed_analyzes", "doubles")
    op.drop_column("detailed_analyzes", "wrong_doubles_above_tg")
    op.drop_column("detailed_analyzes", "wrong_passes")
    op.drop_column("detailed_analyzes", "passes")
    op.drop_column("detailed_analyzes", "moves_marked_doubtful")
    op.drop_column("detailed_analyzes", "wrong_doubles_below_dp")
    op.drop_column("detailed_analyzes", "close_or_actual_cube_decisions")
    op.drop_column("detailed_analyzes", "wrong_takes")
    op.drop_column("detailed_analyzes", "total_cube_decisions")
    op.drop_column("detailed_analyzes", "error_rate_cube")
    op.drop_column("detailed_analyzes", "error_rate_total")
    op.drop_column("detailed_analyzes", "unforced_moves")
    op.drop_column("detailed_analyzes", "rolls_unmarked")
    op.drop_column("detailed_analyzes", "missed_doubles_below_cp")
    op.drop_column("detailed_analyzes", "takes")
    op.drop_column("detailed_analyzes", "missed_doubles_above_cp")
    op.drop_column("detailed_analyzes", "unmarked_moves")
    op.drop_column("detailed_analyzes", "total_moves")
    op.drop_column("detailed_analyzes", "luck_adjusted_result")
    op.drop_column("detailed_analyzes", "actual_result")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "actual_result",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "luck_adjusted_result",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column("total_moves", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column("unmarked_moves", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "missed_doubles_above_cp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column("takes", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "missed_doubles_below_cp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column("rolls_unmarked", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column("unforced_moves", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "error_rate_total",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "error_rate_cube",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "total_cube_decisions", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "wrong_takes",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "close_or_actual_cube_decisions",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "wrong_doubles_below_dp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "moves_marked_doubtful", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column("passes", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "wrong_passes",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "wrong_doubles_above_tg",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column("doubles", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("detailed_analyzes", "rolls_rate_chequer")
    # ### end Alembic commands ###
