"""add_field_name_at_bt

Revision ID: b0c140ffcfbf
Revises: db4d3b7f5181
Create Date: 2025-09-18 11:24:46.031630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c140ffcfbf'
down_revision: Union[str, Sequence[str], None] = 'db4d3b7f5181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('name', sa.String(), nullable=False,default='noname',server_default='noname'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'name')
    # ### end Alembic commands ###
