"""add default to activate_count

Revision ID: cb22f00cda14
Revises: d239c1f8c60b
Create Date: 2025-12-30 14:52:26.091486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb22f00cda14'
down_revision: Union[str, Sequence[str], None] = 'd239c1f8c60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('promocode', 'activate_count', server_default='0', nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
