"""add_tranzaction_field

Revision ID: d1be81ada821
Revises: 361c012b86a0
Create Date: 2025-08-02 23:52:50.963870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1be81ada821'
down_revision: Union[str, Sequence[str], None] = '361c012b86a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analize_payments', sa.Column('tranzaction_id', sa.String(), nullable=False, default="None", server_default="None"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_analize_payments', 'tranzaction_id')
    # ### end Alembic commands ###
