"""add group id ad br

Revision ID: d239c1f8c60b
Revises: b0c140ffcfbf
Create Date: 2025-09-24 13:13:42.525250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd239c1f8c60b'
down_revision: Union[str, Sequence[str], None] = 'b0c140ffcfbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('group_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'group_id')
    # ### end Alembic commands ###
