"""fix promo

Revision ID: dc05570142a7
Revises: 04fe0bf78dbd
Create Date: 2025-07-26 19:34:12.198947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc05570142a7'
down_revision: Union[str, Sequence[str], None] = '04fe0bf78dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocode', sa.Column('analiz_count', sa.Integer(), nullable=True, server_default="0"))
    op.drop_column('promocode', 'discount_days')
    op.add_column('users', sa.Column('analiz_balance', sa.Integer(), nullable=True, server_default="0"))
    op.drop_column('users', 'end_sub_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('end_sub_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'analiz_balance')
    op.add_column('promocode', sa.Column('discount_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('promocode', 'analiz_count')
    # ### end Alembic commands ###
