"""add detailed cube fields to DetailedAnalysis

Revision ID: eba777a3ad10
Revises: 21c7406333d7
Create Date: 2025-07-31 07:39:13.006720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eba777a3ad10"
down_revision: Union[str, Sequence[str], None] = "21c7406333d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "missed_doubles_below_cp", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "missed_doubles_above_cp", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "wrong_doubles_below_sp", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column(
            "wrong_doubles_above_tg", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column("wrong_takes", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column("wrong_passes", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "detailed_analyzes",
        sa.Column("cube_error_rate", sa.Float(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("detailed_analyzes", "cube_error_rate")
    op.drop_column("detailed_analyzes", "wrong_passes")
    op.drop_column("detailed_analyzes", "wrong_takes")
    op.drop_column("detailed_analyzes", "wrong_doubles_above_tg")
    op.drop_column("detailed_analyzes", "wrong_doubles_below_sp")
    op.drop_column("detailed_analyzes", "missed_doubles_above_cp")
    op.drop_column("detailed_analyzes", "missed_doubles_below_cp")
    # ### end Alembic commands ###
