"""add_new_fileld

Revision ID: ec7cc2f983ee
Revises: be34536a652e
Create Date: 2025-08-18 18:52:03.698126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7cc2f983ee'
down_revision: Union[str, Sequence[str], None] = 'be34536a652e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocode_service_quantities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promocode_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('ANALYSIS', 'SHORT_BOARD', name='servicetype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promocode_id'], ['promocode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_promocode_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_promocode_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('ANALYSIS', 'SHORT_BOARD', name='servicetype'), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_promocode_id'], ['user_promocode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('promocode', 'analiz_count')
    op.drop_column('user_promocode', 'current_analize_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_promocode', sa.Column('current_analize_balance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('promocode', sa.Column('analiz_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_table('user_promocode_services')
    op.drop_table('promocode_service_quantities')
    # ### end Alembic commands ###
