"""fix

Revision ID: f47ccf40032c
Revises: dcec45b121d6
Create Date: 2025-08-19 04:54:07.793726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47ccf40032c'
down_revision: Union[str, Sequence[str], None] = 'dcec45b121d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_promocode_services', 'remaining_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_promocode_services', 'remaining_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
